
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import AccountNavbar from '@/components/AccountNavbar';
import Footer from '@/components/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Account Page",
  description: "Generated by create next app",
};

/*
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
*/

export default async function AccountLayout({ children }: { children: React.ReactNode }) {
    const cookieStore = await cookies();
    const role = cookieStore.get('user_role')?.value;
    const token = cookieStore.get('token')?.value;

  // ป้องกันชั้นที่ 2 นอกจาก Middleware (เผื่อ Middleware หลุด)
  if (!token || (role !== 'account' && role !== 'root')) {
    redirect('/auth');
  }


  return (
    <>
      <div
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AccountNavbar />
            <main>
               {children}
            </main>
        <Footer />
      </div>
    </>
  );
}
